apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nayris

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: nestjs-server
    path: patch-deployment.yaml
  - target:
      kind: Service
      name: nestjs-server
    path: patch-service.yaml
