services:
  server:
    container_name: nayris-server
    image: ghcr.io/kounex/nayris/nestjs-server:latest
    environment:
      - CLOUDFLARE_TEAM_DOMAIN=your-team-name # <--- ADD THIS
    ports:
      - "4444:4444"
    restart: unless-stopped

  client:
    container_name: nayris-client
    image: ghcr.io/kounex/nayris/nginx-client:latest
    ports:
      - "8888:8080"
    depends_on:
      - server
    restart: unless-stopped
